name: Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag to publish (e.g., v1.2.3)'
        required: true
      release_name:
        description: 'Optional title for the release (defaults to the tag)'
        required: false

jobs:
  build-release:
    runs-on: ubuntu-latest
    env:
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Prepare release signing
        if: ${{ env.ANDROID_KEYSTORE_BASE64 != '' }}
        run: |
          set -euo pipefail
          mkdir -p ~/.gradle
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > release.keystore
          cat <<EOF >> ~/.gradle/gradle.properties
          RELEASE_STORE_FILE=release.keystore
          RELEASE_STORE_PASSWORD=$ANDROID_KEYSTORE_PASSWORD
          RELEASE_KEY_ALIAS=$ANDROID_KEY_ALIAS
          RELEASE_KEY_PASSWORD=$ANDROID_KEY_PASSWORD
          EOF

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build release APK
        run: ./gradlew clean assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

  publish-release:
    needs: build-release
    runs-on: ubuntu-latest
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release
          path: dist

      - name: Determine release metadata
        id: release_meta
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ] && [ -n "${GITHUB_REF_NAME}" ]; then
            echo "tag_name=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
            echo "release_name=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"
          elif [ -n "${INPUT_TAG_NAME}" ]; then
            echo "tag_name=${INPUT_TAG_NAME}" >> "$GITHUB_OUTPUT"
            if [ -n "${INPUT_RELEASE_NAME}" ]; then
              echo "release_name=${INPUT_RELEASE_NAME}" >> "$GITHUB_OUTPUT"
            else
              echo "release_name=${INPUT_TAG_NAME}" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "::error::No release tag provided." >&2
            exit 1
          fi
        env:
          GITHUB_REF_TYPE: ${{ github.ref_type }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
          INPUT_TAG_NAME: ${{ github.event.inputs.tag_name }}
          INPUT_RELEASE_NAME: ${{ github.event.inputs.release_name }}

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/app-release.apk
          tag_name: ${{ steps.release_meta.outputs.tag_name }}
          name: ${{ steps.release_meta.outputs.release_name }}
          target_commitish: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
